### ISSUE TITLE
Add support for Kotest

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/selfie#122]
If you are only using Kotest with JUnit5, then Selfie will work perfect out of the box with `selfie-runner-junit5`.

If you want, you can instead use `selfie-runner-kotest`. This has the slight disadvantage that you will have to register selfie with Kotest, while `selfie-runner-junit5` requires no registration. But it has the advantage that it works with Kotlin Multiplatform, so you can take your selfies anywhere that Kotlin and Selfie can run.

Other differences between `selfie-runner-kotest` and `selfie-runner-junit5`
- system property `selfie.settings` -> env `SELFIE_SETTINGS`
- 

This issue is tracking the completion of the JVM version of `selfie-runner-kotest`. For JS, see #186. Other platforms are welcome as well.

- [x] create `selfie-runner-kotest` and `undertest-kotest` #185
- [x] copy selfie-runner-junit's `Harness` class into a `HarnessKotest` #185
- [x] copy `FSJava` and name it `FSOkio`, implement with okio #188
- [x] copy `SnapshotFileLayoutJUnit` and name it `SnapshotFileLayoutKotest` #191
- [x] now the tricky part, implement `SnapshotStorage`, which should work in combination with Kotest's `prepareSpec/finalizeSpec/beforeTest/afterTest` hooks #201
- [x] the hardest part is garbage-collecting stale snapshots, leave this out at first https://github.com/diffplug/selfie/pull/216

**Comment by nedtwigg** [comment]
There's two approaches:

- regular JUnit5 runner (#208)
- kotest-native multiplatform runner (tracked above)

Documenting this will be a bit tricky...
