### ISSUE TITLE
Inline snapshot roadmap

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/selfie#48]
The bones of inline snapshots landed in:

- #23 

Things which we'll need to implement
- [x] handle `toBe(LITERAL)`, not just `toBe_TODO()` #49
- [x] breakup long integers `1_000` not `1000`, `1_000_000` not `1000000` #70
- [x] implement `LongSelfie` #71 
- [x] implement `BooleanSelfie` #72 
- [x] implement `StringLiteral` single-line #56 
- [x] implement `StringLiteral` multi-line
    - [x] Kotlin `"""` https://github.com/diffplug/selfie/pull/90
    - [x] Java 15+ `"""` https://github.com/diffplug/selfie/pull/87
    - ~~Java <15 `"foo\n" + "bar\n"`, but we should support this last~~ not necessary for 1.0
- [x] whitespace inside the toBe (e.g. `.toBe(  35  )` instead of `.toBe(35)`, and also newlines
  - we need to "parse" the file enough to survive auto formatters changing the location of the literal
  - https://github.com/diffplug/selfie/pull/86
- [x] error message if it isn't a literal (e.g. `.toBe(27 + 8)`)
  - before we ever change a snapshot, we always make sure first that we can parse it correctly as a sanity check
  - tell the user that it must be a literal, and point them to `toBe_TODO()` to get back on track
  - https://github.com/diffplug/selfie/pull/86

**Comment by nedtwigg** [comment]
@jknack something to keep in mind for Kotlin multiline string literals:

- https://www.baeldung.com/kotlin/string-templates#2-using-string-interpolation-with-literals

**Comment by nedtwigg** [comment]
Complete! Huzzah!
