### ISSUE TITLE
Javascript roadmap

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/selfie#84]
- [ ] move tests from `selfie-lib/src/jvmTest` into `commonTest` one by one
  - will require implementing some `TODO` parts of the `selfie-lib` JS
- [ ] create `selfie-runner-mocha` for Node.js testing
  - most of the implementation can be copied from `selfie-runner-junit5`, which is only 600 LOC (+120 more LOC comments)
  - recommended order
    - copy `FSJava` and name it `FSNode`, bring in Okio (or similar) to implement
    - copy `SnapshotFileLayoutJUnit5` and name it `SnapshotFileLayoutMocha`
    - now the tricky part, implement `SnapshotStorage`, which works in combination with Mocha's `before/after/beforeEach/afterEach` [hooks](https://mochajs.org/#hooks) to map `Selfie` calls to snapshot files and test sourcecode
    - the hardest part is garbage-collecting stale snapshots, leave this out at first
- [ ] create `selfie-runner-karma` for in-browser testing
  - piping the filesystem to/from the browser is tricky, but [karma-snapshot](https://www.npmjs.com/package/karma-snapshot) figured it out
  - this is why the `FS` is provided by `SnapshotStorage`

**Comment by nedtwigg** [comment]
Useful stuff here

- https://github.com/kotest/kotest/pull/3805/commits/94e6098ff4d780ccdeecf93aaa66f98271749589

**Comment by nedtwigg** [comment]
Maybe deploy to JSR first, good overview here

- https://open.substack.com/pub/allthingstypescript/p/a-brief-introduction-to-javascript?r=2kgph9&utm_medium=ios
